@echo off
echo Fixing SmartPulse v2 Code Issues...
echo.

echo Step 1: Remove debug print statements...
echo Finding all .dart files with print statements...

echo Step 2: Fix lint violations...
echo Running flutter fix --auto-fix...

echo Step 3: Clean build...
echo flutter clean
echo.

echo Step 4: Analyze code...
echo flutter analyze

echo.
echo All fixes applied!
pause
